name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: us-west-2

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      run: |
        IMAGE_TAG=$(date +%s)
        docker build -t hello-world:${IMAGE_TAG} .
        docker tag hello-world:${IMAGE_TAG} <AWS_ACCOUNT_ID>.dkr.ecr.us-west-2.amazonaws.com/hello-world:${IMAGE_TAG}
        docker push <AWS_ACCOUNT_ID>.dkr.ecr.us-west-2.amazonaws.com/hello-world:${IMAGE_TAG}
      env:
        AWS_REGION: us-west-2

    - name: Deploy to ECS
      id: deploy-ecs
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: "hello-world-task"
        service: "hello-world-service"
        cluster: "hello-world-cluster"
        wait-for-service-stability: true
        region: us-west-2
